# Generated by Django 4.2.7 on 2026-06-11 17:26

import archives.mixins.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='案卷标题')),
                ('description', models.TextField(verbose_name='案卷描述')),
                ('archive_number', models.CharField(max_length=100, unique=True, verbose_name='案卷编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交审核时间')),
            ],
            options={
                'verbose_name': '案卷',
                'verbose_name_plural': '案卷',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, archives.mixins.model_mixins.ArchiveDataMixin),
        ),
        migrations.CreateModel(
            name='ArchiveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='案卷标题')),
                ('description', models.TextField(verbose_name='案卷描述')),
                ('archive_number', models.CharField(max_length=100, verbose_name='案卷编号')),
                ('category_id', models.IntegerField(verbose_name='分类ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], max_length=20, verbose_name='状态')),
                ('snapshot_data', models.JSONField(verbose_name='快照数据')),
                ('change_reason', models.TextField(blank=True, verbose_name='修改原因')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='archives.archive', verbose_name='关联案卷')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_archive_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '案卷版本快照',
                'verbose_name_plural': '案卷版本快照',
                'ordering': ['archive', '-version_number'],
                'unique_together': {('archive', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='失败次数')),
                ('last_attempt_time', models.DateTimeField(blank=True, null=True, verbose_name='最后尝试时间')),
                ('lock_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间')),
            ],
            options={
                'verbose_name': '登录尝试记录',
                'verbose_name_plural': '登录尝试记录',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('theme', models.CharField(choices=[('light', '浅色主题'), ('dark', '深色主题'), ('auto', '跟随系统')], default='light', max_length=20, verbose_name='主题')),
                ('language', models.CharField(choices=[('zh-CN', '简体中文'), ('en', 'English'), ('ja', '日本語')], default='zh-CN', max_length=20, verbose_name='语言')),
                ('email_notification', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('sound_effect', models.BooleanField(default=False, verbose_name='音效')),
                ('auto_save', models.BooleanField(default=True, verbose_name='自动保存')),
                ('page_size', models.IntegerField(default=10, verbose_name='每页条数')),
                ('sidebar_collapsed', models.BooleanField(default=False, verbose_name='侧边栏收起')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='待办标题')),
                ('description', models.TextField(blank=True, verbose_name='待办描述')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('todo_type', models.CharField(choices=[('general', '普通'), ('review', '审核'), ('notification', '通知')], default='general', max_length=20, verbose_name='待办类型')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='archives.archive', verbose_name='关联案卷')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reject_comment', models.TextField(verbose_name='驳回意见')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, verbose_name='驳回时间')),
                ('data_before', models.JSONField(verbose_name='修改前数据')),
                ('data_after', models.JSONField(verbose_name='修改后数据')),
                ('field_changes', models.JSONField(verbose_name='字段变更详情')),
                ('is_resubmitted', models.BooleanField(default=False, verbose_name='是否已重新提交')),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True, verbose_name='重新提交时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_records', to='archives.archive', verbose_name='关联案卷')),
                ('reject_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_records', to='archives.archiveversion', verbose_name='驳回时版本')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_records', to=settings.AUTH_USER_MODEL, verbose_name='驳回人')),
            ],
            options={
                'verbose_name': '驳回记录',
                'verbose_name_plural': '驳回记录',
                'ordering': ['-rejected_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='archives.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archive_number', models.CharField(max_length=100, verbose_name='案卷编号')),
                ('archive_title', models.CharField(blank=True, max_length=200, verbose_name='案卷标题')),
                ('action_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '预览')], max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('change_content', models.JSONField(blank=True, null=True, verbose_name='变更内容')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='archives.archive', verbose_name='关联案卷')),
            ],
            options={
                'verbose_name': '案卷操作日志',
                'verbose_name_plural': '案卷操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='archives.category', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='archive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_archives', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='archive',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_archives', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
