# Generated by Django 4.2.7 on 2026-06-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_userprofile_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(choices=[('zh-CN', '简体中文'), ('en', 'English'), ('ja', '日本語')], default='zh-CN', max_length=20, verbose_name='语言'),
        ),
        migrations.CreateModel(
            name='ArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_number', models.CharField(max_length=100, verbose_name='案卷编号')),
                ('archive_title', models.CharField(blank=True, max_length=200, verbose_name='案卷标题')),
                ('action_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '预览')], max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('change_content', models.JSONField(blank=True, null=True, verbose_name='变更内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='archives.archive', verbose_name='关联案卷')),
            ],
            options={
                'verbose_name': '案卷操作日志',
                'verbose_name_plural': '案卷操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
