# Generated by Django 4.2.7 on 2026-06-10 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0005_setup_archive_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='案卷标题')),
                ('description', models.TextField(verbose_name='案卷描述')),
                ('archive_number', models.CharField(max_length=100, verbose_name='案卷编号')),
                ('category_id', models.IntegerField(verbose_name='分类ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], max_length=20, verbose_name='状态')),
                ('snapshot_data', models.JSONField(verbose_name='快照数据')),
                ('change_reason', models.TextField(blank=True, verbose_name='修改原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='archives.archive', verbose_name='关联案卷')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_archive_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '案卷版本快照',
                'verbose_name_plural': '案卷版本快照',
                'ordering': ['archive', '-version_number'],
                'unique_together': {('archive', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='RejectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reject_comment', models.TextField(verbose_name='驳回意见')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, verbose_name='驳回时间')),
                ('data_before', models.JSONField(verbose_name='修改前数据')),
                ('data_after', models.JSONField(verbose_name='修改后数据')),
                ('field_changes', models.JSONField(verbose_name='字段变更详情')),
                ('is_resubmitted', models.BooleanField(default=False, verbose_name='是否已重新提交')),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True, verbose_name='重新提交时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_records', to='archives.archive', verbose_name='关联案卷')),
                ('reject_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reject_records', to='archives.archiveversion', verbose_name='驳回时版本')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_records', to=settings.AUTH_USER_MODEL, verbose_name='驳回人')),
            ],
            options={
                'verbose_name': '驳回记录',
                'verbose_name_plural': '驳回记录',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
